name: HEX-finder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.18
  - pip
  - wget
  - gunzip
  - samtools
  - bedtools
  - numpy
  - pandas
  - pip:
    - "tensorflow[and-cuda]>=2.15"
    - keras-tcn
    - npy_append_array
    - colorama
    - biopython
    - plotly